name: ci

on:
  push:
    branches:
    - 'main'
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: bliitzz
      APP: simple-node-app
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: "${{ env.DOCKERHUB_USERNAME }}/${ env.APP }}:latest,${{ env.DOCKERHUB_USERNAME}}/${{ env.APP }}:${{ steps.vars.outputs.sha_short }}"